language: node_js
node_js:
- '0.10'
- '0.8'
- '0.6'
script: npm run-script ci
env:
  global:
  - BUSTER_TEST_OPT="--reporter specification"
  - SAUCE_USERNAME=vannevartech-unitify
  - secure: "RSokvbT3BLK8Y+GDf3Mwc6UZy5IhE05O4xCroa/qECbnTgIv+J7af50al6tvkoRoSEVBkhvl7FvEqjDyMiKczw4GbU5OqNSITawUYsVBoVoHFTuqi1Hak2czct1KCQA9G5kVR3pjkJvjzuUeqnpWIz8coBEB7BwiULwW2Gi6w2s="
