language: node_js
node_js:
- '0.10'
- '0.8'
- '0.6'
script: npm run-script ci
env:
  global:
  - BUSTER_TEST_OPT="--reporter specification"
  - SAUCE_USERNAME=scothis-unitd
  - secure: LxrBx5l/hFBSqJmGTIZXPparbspx7AOOpFrtTuLtFgvO2HG/6i6qZFqFm3p+Jrva1/2pmyDP7Q5UbtWreKe7Uj0CBW0B3RrsYJ79rmnY54aGavYO+9O7/0M6zDahXGiCNjoH5rY3ZC9HEWj9lHQm7j//JsBKSz1ZM6hStom1c64=
